### ISSUE TITLE
To which bug is this a reproduction?

### ISSUE THREAD

**Issue by cirosantilli** [miguelinux/overlay-9p-issue#1]

**Comment by cirosantilli** [comment]
Ah, ok: https://lore.kernel.org/lkml/CAOQ4uxhEXCDAc8aCQpdgi-PPtw+X8pyBV-HUted+R6ifqaCVUw@mail.gmail.com/

**Comment by poige** [comment]
LOL, I've just made the same thing and then realised I'd better check closed items too. )))
